//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductVisualizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PV_Linker
    {
        public int Id { get; set; }
        public int SoftwareId { get; set; }
        public Nullable<int> GEOId { get; set; }
        public Nullable<int> IndustryId { get; set; }
        public Nullable<int> PersonaId { get; set; }
        public Nullable<int> PhaseId { get; set; }
        public Nullable<int> BIMUseId { get; set; }
    }
}
