//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductVisualizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PV_Software
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Features { get; set; }
        public byte[] Image { get; set; }
        public string ProductPage { get; set; }
        public string TrainingCourses { get; set; }
        public string Version { get; set; }
        public string Cost { get; set; }
        public string Language { get; set; }
    }
}
