//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductVisualizer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProductVisualizerEntities : DbContext
    {
        public ProductVisualizerEntities()
            : base("name=ProductVisualizerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PV_BIMUse> PV_BIMUse { get; set; }
        public virtual DbSet<PV_GEO> PV_GEO { get; set; }
        public virtual DbSet<PV_Industry> PV_Industry { get; set; }
        public virtual DbSet<PV_Joiner> PV_Joiner { get; set; }
        public virtual DbSet<PV_Linker> PV_Linker { get; set; }
        public virtual DbSet<PV_Persona> PV_Persona { get; set; }
        public virtual DbSet<PV_Phase> PV_Phase { get; set; }
        public virtual DbSet<PV_Software> PV_Software { get; set; }
        public virtual DbSet<AllDetail> AllDetails { get; set; }
    }
}
